In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [13]:
shape = (2,2,2,2,2, 2)
psi_new=np.ones(shape)/np.prod(shape)
print(psi_new)

[[[[[[0.015625 0.015625]
     [0.015625 0.015625]]

    [[0.015625 0.015625]
     [0.015625 0.015625]]]


   [[[0.015625 0.015625]
     [0.015625 0.015625]]

    [[0.015625 0.015625]
     [0.015625 0.015625]]]]



  [[[[0.015625 0.015625]
     [0.015625 0.015625]]

    [[0.015625 0.015625]
     [0.015625 0.015625]]]


   [[[0.015625 0.015625]
     [0.015625 0.015625]]

    [[0.015625 0.015625]
     [0.015625 0.015625]]]]]




 [[[[[0.015625 0.015625]
     [0.015625 0.015625]]

    [[0.015625 0.015625]
     [0.015625 0.015625]]]


   [[[0.015625 0.015625]
     [0.015625 0.015625]]

    [[0.015625 0.015625]
     [0.015625 0.015625]]]]



  [[[[0.015625 0.015625]
     [0.015625 0.015625]]

    [[0.015625 0.015625]
     [0.015625 0.015625]]]


   [[[0.015625 0.015625]
     [0.015625 0.015625]]

    [[0.015625 0.015625]
     [0.015625 0.015625]]]]]]


In [10]:
d = 3
i_neighbours = np.array([1, 0])
perm = np.array([0, 0, 1, 1])
i = 1
j = 0
for k in range(d-1):
        index = (i_neighbours[k],) + tuple(perm[k*(d-1):(k+1)*(d-1)]) + (i,) + (j,) + tuple(i_neighbours[:k]) + tuple(i_neighbours[k+1:])
        print(index)

(1, 0, 0, 1, 0, 0)
(0, 1, 1, 1, 0, 1)


In [4]:
def initialize_psi(degree):
    shape = tuple([2] * degree + [2] * degree)  # Create shape dynamically
    psi = np.zeros(shape)
    return psi

def iterate_indices(indices, shape):
    if len(indices) == len(shape):
        # Base case: All indices are filled, yield the tuple
        yield tuple(indices)
    else:
        # Recursive case: Fill the next index
        for i in range(shape[len(indices)]):
            indices.append(i)
            yield from iterate_indices(indices, shape)
            indices.pop()  # Backtrack

# Example function using generalized indices
def example_function(shape):
    for indices in iterate_indices([], shape):
        print(indices[5])

degree = 4  # Example degree
shape = tuple([2] * degree + [2] * degree)
example_function(shape)


0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
