In [3]:
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

In [4]:
def gen_configurations(d):
    """
    returns all possible configurations of d-1 neighbours
    """
    return np.array(np.meshgrid(*[[0, 1]] * (d-1))).T.reshape(-1, d-1)

In [5]:
def respect_rule(rule, i, j, rest_config):
        outer_density=j+np.sum(rest_config)
        if rule[outer_density]=='0':
            return True if i==0 else False
        elif rule[outer_density]=='1':
            return True if i==1 else False
        elif rule[outer_density]=='+':
            return True
        elif rule[outer_density]=='-':
            return False

def rule_satisfied(sigma_i, sigma_j, configuration, rule_plus):
    """
    returns True if the configuration satisfies the rule, False otherwise
    """

    if rule_plus:
        if np.sum(np.concatenate((configuration, np.array([sigma_j])))*sigma_i) == 0:
            return True
        else:
            return False
    else:
        if np.sum(np.concatenate((configuration, np.array([sigma_j])))*sigma_i) == 0 and sigma_i + sigma_j + np.sum(configuration) > 0:
            return True
        else:
            return False

In [6]:
def neighbouring_warnings_allow(sigma_i, configuration, warning_prev):
    """
    returns True if the neighbouring warnings allow the configuration, False otherwise
    """
    
    for k in range(len(configuration)):
        sigma_k = configuration[k]
        if warning_prev[sigma_k, sigma_i] == 0:
            return False

    return True

In [19]:
def warning_propagation_update(warning_prev, rule, d):
    """
    neighbouring warnings (list): list of warnings of neighbouring nodes k except j

    returns warning i -> j (2x2 array)
    """
    warning = np.zeros((2, 2))
    for sigma_i in range(2):
        for sigma_j in range(2):
            configurations = gen_configurations(d)
            for configuration in configurations:
                if respect_rule(rule, sigma_i, sigma_j, configuration) and neighbouring_warnings_allow(sigma_i, configuration, warning_prev):
                    warning[sigma_i, sigma_j] = 1
                    break
    return warning

In [20]:
def warning_propagation(warning_init, rule, num_iters = 100):
    d = len(rule)-1
    warning = warning_init.copy()
    converged = False

    for _ in tqdm(np.arange(num_iters)):
        warning_prev = warning.copy()
        warning[:, :] = warning_propagation_update(warning_prev, rule, d)
        if np.array_equal(warning, warning_prev):
            converged = True
            break

    
    return warning, converged

In [21]:
warning_init_space = []
for i in range(2):
    for j in range(2):
        for k in range(2):
            for l in range(2):
                warning_init_space.append(np.array([[i, j], [k, l]]))

rule = ['1', '0', '0', '0']

for warning_init in warning_init_space:
    warning_fixed_point, converged = warning_propagation(warning_init, rule=rule, num_iters = 1000)
    print(warning_init)
    print("Did it converge?", converged)
    print(warning_fixed_point)
    print('-------------------')

  0%|          | 0/1000 [00:00<?, ?it/s]


[[0 0]
 [0 0]]
Did it converge? True
[[0 0]
 [0 0]]
-------------------


  0%|          | 1/1000 [00:00<00:00, 2155.35it/s]


[[0 0]
 [0 1]]
Did it converge? True
[[0 0]
 [0 0]]
-------------------


  0%|          | 3/1000 [00:00<00:00, 4903.71it/s]


[[0 0]
 [1 0]]
Did it converge? True
[[1 1]
 [1 0]]
-------------------


  0%|          | 3/1000 [00:00<00:00, 5640.03it/s]


[[0 0]
 [1 1]]
Did it converge? True
[[1 1]
 [1 0]]
-------------------


  0%|          | 4/1000 [00:00<00:00, 7650.35it/s]


[[0 1]
 [0 0]]
Did it converge? True
[[1 1]
 [1 0]]
-------------------


  0%|          | 4/1000 [00:00<00:00, 7605.27it/s]


[[0 1]
 [0 1]]
Did it converge? True
[[1 1]
 [1 0]]
-------------------


  0%|          | 1/1000 [00:00<00:00, 4258.18it/s]


[[0 1]
 [1 0]]
Did it converge? True
[[1 1]
 [1 0]]
-------------------


  0%|          | 1/1000 [00:00<00:00, 4364.52it/s]


[[0 1]
 [1 1]]
Did it converge? True
[[1 1]
 [1 0]]
-------------------


  0%|          | 5/1000 [00:00<00:00, 7530.17it/s]


[[1 0]
 [0 0]]
Did it converge? True
[[1 1]
 [1 0]]
-------------------


  0%|          | 5/1000 [00:00<00:00, 9485.08it/s]


[[1 0]
 [0 1]]
Did it converge? True
[[1 1]
 [1 0]]
-------------------


  0%|          | 3/1000 [00:00<00:00, 7999.31it/s]


[[1 0]
 [1 0]]
Did it converge? True
[[1 1]
 [1 0]]
-------------------


  0%|          | 3/1000 [00:00<00:00, 8289.14it/s]


[[1 0]
 [1 1]]
Did it converge? True
[[1 1]
 [1 0]]
-------------------


  0%|          | 2/1000 [00:00<00:00, 4609.13it/s]


[[1 1]
 [0 0]]
Did it converge? True
[[1 1]
 [1 0]]
-------------------


  0%|          | 2/1000 [00:00<00:00, 3787.18it/s]


[[1 1]
 [0 1]]
Did it converge? True
[[1 1]
 [1 0]]
-------------------


  0%|          | 0/1000 [00:00<?, ?it/s]


[[1 1]
 [1 0]]
Did it converge? True
[[1 1]
 [1 0]]
-------------------


  0%|          | 1/1000 [00:00<00:00, 2078.45it/s]

[[1 1]
 [1 1]]
Did it converge? True
[[1 1]
 [1 0]]
-------------------


In [22]:
warning_init_space = []
for i in range(2):
    for j in range(2):
        for k in range(2):
            for l in range(2):
                warning_init_space.append(np.array([[i, j], [k, l]]))

rule = ['+', '1', '0', '0', '0', '0']

for warning_init in warning_init_space:
    warning_fixed_point, converged = warning_propagation(warning_init, rule, num_iters = 1000)
    print(warning_init)
    print("Did it converge?", converged)
    print(warning_fixed_point)
    print('-------------------')

  0%|          | 0/1000 [00:00<?, ?it/s]


[[0 0]
 [0 0]]
Did it converge? True
[[0 0]
 [0 0]]
-------------------


  0%|          | 1/1000 [00:00<00:00, 1477.91it/s]


[[0 0]
 [0 1]]
Did it converge? True
[[0 0]
 [0 0]]
-------------------


100%|██████████| 1000/1000 [00:00<00:00, 7338.05it/s]


[[0 0]
 [1 0]]
Did it converge? False
[[1 0]
 [1 1]]
-------------------


100%|██████████| 1000/1000 [00:00<00:00, 7789.85it/s]


[[0 0]
 [1 1]]
Did it converge? False
[[1 0]
 [1 1]]
-------------------


100%|██████████| 1000/1000 [00:00<00:00, 7512.53it/s]


[[0 1]
 [0 0]]
Did it converge? False
[[1 1]
 [0 0]]
-------------------


100%|██████████| 1000/1000 [00:00<00:00, 7529.61it/s]


[[0 1]
 [0 1]]
Did it converge? False
[[1 1]
 [0 0]]
-------------------


  0%|          | 1/1000 [00:00<00:00, 3560.53it/s]


[[0 1]
 [1 0]]
Did it converge? True
[[1 1]
 [1 1]]
-------------------


  0%|          | 1/1000 [00:00<00:00, 3292.23it/s]


[[0 1]
 [1 1]]
Did it converge? True
[[1 1]
 [1 1]]
-------------------


  0%|          | 0/1000 [00:00<?, ?it/s]


[[1 0]
 [0 0]]
Did it converge? True
[[1 0]
 [0 0]]
-------------------


  0%|          | 1/1000 [00:00<00:00, 2341.88it/s]


[[1 0]
 [0 1]]
Did it converge? True
[[1 0]
 [0 0]]
-------------------


100%|██████████| 1000/1000 [00:00<00:00, 7139.03it/s]


[[1 0]
 [1 0]]
Did it converge? False
[[1 0]
 [1 1]]
-------------------


100%|██████████| 1000/1000 [00:00<00:00, 7477.69it/s]


[[1 0]
 [1 1]]
Did it converge? False
[[1 0]
 [1 1]]
-------------------


100%|██████████| 1000/1000 [00:00<00:00, 7445.22it/s]


[[1 1]
 [0 0]]
Did it converge? False
[[1 1]
 [0 0]]
-------------------


100%|██████████| 1000/1000 [00:00<00:00, 7484.26it/s]


[[1 1]
 [0 1]]
Did it converge? False
[[1 1]
 [0 0]]
-------------------


  0%|          | 1/1000 [00:00<00:00, 3890.82it/s]


[[1 1]
 [1 0]]
Did it converge? True
[[1 1]
 [1 1]]
-------------------


  0%|          | 0/1000 [00:00<?, ?it/s]

[[1 1]
 [1 1]]
Did it converge? True
[[1 1]
 [1 1]]
-------------------
